"""
Property test — Task 4.5 of spec ``kmbox-net-integration``.

# Feature: kmbox-net-integration, Property 1: Encryption flag governs
#   every send-site routing.

**Property 1: Encryption flag governs every send-site routing**

    *For any* sequence of public-method calls on :class:`KmBoxNetDriver`
    (``move`` / ``click`` / ``click_button`` / ``mouse_down`` /
    ``mouse_up`` / ``key_press`` / ``scroll``) — including sequences in
    which one or more individual ``kmNet.*`` invocations raise an
    exception — when the driver is constructed with
    ``use_encryption=True`` the test SHALL observe **zero** invocations of
    any plaintext ``kmNet.{move, left, right, middle, wheel, keydown,
    keyup}`` function across the entire sequence. Conversely, when the
    driver is constructed with ``use_encryption=False`` the test SHALL
    observe **zero** invocations of any encrypted
    ``kmNet.enc_{move, left, right, middle, wheel, keydown, keyup}``
    function.

**Validates: Requirements 4.1, 4.2, 4.4, 4.5, 4.6**

Implementation notes
--------------------
The driver routes every send-site through ``KmBoxNetDriver._dispatch_call``,
which selects between ``_PLAINTEXT_FN`` and ``_ENCRYPTED_FN`` based on
``use_encryption`` (see ``input/kmbox_net_driver.py`` and ``design.md`` §
"``_dispatch_call`` — encrypted-vs-plaintext canonical table"). Property 1
is the formal statement that this single-table consultation is the only
place where the encryption flag is read at runtime: there is no fall-back
path from encrypted to plaintext on per-call failure (Req 4.6) and no
stray ``kmNet.left`` (or any other plaintext attribute) call leaks
through while encryption is on.

Per-call exception injection (Req 4.6)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Each method-call entry generated by Hypothesis carries a ``should_raise``
flag. Before invoking the method we set a shared latch consulted by every
``kmNet.*`` mock attribute's ``side_effect``; while the latch is True any
``kmNet.*`` call raises ``RuntimeError("injected_mock_failure")``. After
the method returns we clear the latch. The driver's per-method exception
handlers (``send_click`` / ``click_button`` / ``mouse_down`` /
``mouse_up`` / ``key_press`` / ``scroll`` all log-and-swallow per the
existing contract; ``send_move`` re-raises per Req 1.8) decide whether to
propagate or absorb the failure — the property holds either way because a
dropped (or partially-dropped) command contributes nothing to either side
of the count comparison.

Threading and timing patches
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* ``threading.Thread`` is replaced with a synchronous fake (``_SyncFakeThread``)
  so :meth:`KmBoxNetDriver.click`'s worker (which calls ``send_click`` and
  therefore the dispatch path under test) executes inline rather than on a
  real daemon. The fake also tolerates being constructed before
  ``__init__`` returns (the ``_connect()`` worker uses the same primitive
  to bound ``kmNet.init`` against the 5-second cap); with a mock that
  returns ``0`` immediately the worker completes inline and the bounded
  ``queue.get`` succeeds on the first attempt.
* ``time.sleep`` is replaced with a no-op so neither the click hold (in
  ``send_click`` / ``click_button``) nor the keyboard hold (in
  ``key_press``) wastes wall-clock time. The driver's rate-limit reads
  ``time.monotonic`` (not ``time.sleep``) and is left untouched; clicks
  within the ``1.0 / target_cps`` window may legitimately drop, which is
  fine — a dropped click contributes nothing to either side of the count
  comparison.

Method-call generator
~~~~~~~~~~~~~~~~~~~~~
The strategy is ``lists(one_of(...))`` over a tagged-tuple shape
``(method_name, args_tuple, should_raise)``. Move arguments are drawn
from ``[-100.0, 100.0]`` so they pass the Req 1.4 finite/range gate
without exercising the no-op branch (which is covered by Property 3).
Button identifiers cover the full accepted set on each method —
``"left"`` / ``"right"`` / ``"middle"`` and the DD-compatible integer
codes — so the property exercises both ``_BUTTON_EDGE`` and
``_BUTTON_HOLD`` resolution. ``key_press`` uses ``vk_code=0x41`` (the
``A`` key, present in :meth:`KmBoxNetDriver._vk_to_hid`) and
``hold_ms=0`` so the deterministic Req 4.8 hold collapses to a no-op
``time.sleep(0)`` regardless of whether ``time.sleep`` is patched.
"""

from __future__ import annotations

from typing import Any, Iterable, List, Tuple
from unittest.mock import MagicMock, patch

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from input import kmbox_net_driver
from input.kmbox_net_driver import ConnectionStatus, KmBoxNetDriver


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Sentinel constructor args reused across every driver instance built in
# this module. Values mirror the live ``config.yaml`` entries.
_TEST_IP = "192.168.2.188"
_TEST_PORT = "6234"
_TEST_UUID = "00000000-0000-0000-0000-000000000000"

# The seven plaintext ``kmNet.*`` attributes that MUST observe zero calls
# while ``use_encryption=True`` (Req 4.1 / 4.2 / 4.4 / 4.5). These names
# are the values of ``KmBoxNetDriver._PLAINTEXT_FN``; encoding them
# locally (rather than introspecting the class) keeps the assertion
# auditable against the requirement text.
_PLAINTEXT_ATTRS: Tuple[str, ...] = (
    "move", "left", "right", "middle", "wheel", "keydown", "keyup",
)

# The matching encrypted attributes — MUST observe zero calls while
# ``use_encryption=False``.
_ENCRYPTED_ATTRS: Tuple[str, ...] = tuple(f"enc_{a}" for a in _PLAINTEXT_ATTRS)

# All ``kmNet.*`` attributes the driver may invoke through
# ``_dispatch_call``. The exception-injection ``side_effect`` is wired to
# every one of these so the test does not need to know in advance which
# attribute a given driver method will reach.
_ALL_DISPATCH_ATTRS: Tuple[str, ...] = _PLAINTEXT_ATTRS + _ENCRYPTED_ATTRS

# Identifier sets accepted by the click-edge and hold-edge button
# resolvers respectively (see ``KmBoxNetDriver._BUTTON_EDGE`` /
# ``_BUTTON_HOLD``). Drawn from with ``sampled_from`` so Hypothesis
# explores both the string and integer branches.
_CLICK_BUTTON_IDS: Tuple[Any, ...] = ("left", "right", "middle", 1, 2, 4, 8, 16, 32)
_HOLD_BUTTON_IDS: Tuple[Any, ...] = ("left", "right", "middle", 1, 2, 3)


# ---------------------------------------------------------------------------
# Synchronous thread fake
# ---------------------------------------------------------------------------


class _SyncFakeThread:
    """
    Drop-in for :class:`threading.Thread` whose ``start()`` runs the target
    inline.

    Two driver paths spawn ``threading.Thread`` instances:

    * :meth:`KmBoxNetDriver._connect` — bounds ``kmNet.init`` against the
      5-second cap by harvesting the worker result through a
      ``queue.Queue``. With a mock that returns ``0`` immediately the
      worker completes inline and the bounded ``queue.get`` succeeds on
      the first attempt.
    * :meth:`KmBoxNetDriver.click` — admits a click and spawns a worker
      thread that calls :meth:`send_click`, which in turn issues two
      ``_dispatch_call("left", ...)`` invocations (the down and up edges).
      Running this worker inline lets the property observe the dispatch
      attempts in the same call frame as the ``click()`` invocation.

    ``is_alive()`` returns ``False`` permanently so the
    ``BaseMouse.click_thread.is_alive()`` short-circuit in
    :meth:`KmBoxNetDriver.click` never blocks subsequent admissions on a
    phantom in-flight worker. ``join()`` is a no-op so any future caller
    that joins on the thread does not deadlock.
    """

    __slots__ = ("_target", "_args", "_kwargs")

    def __init__(
        self,
        *args: Any,
        target: Any = None,
        args_kw: Any = None,
        kwargs: Any = None,
        name: Any = None,
        daemon: Any = None,
        **_extra: Any,
    ) -> None:
        # ``threading.Thread`` accepts target/args/kwargs both positionally
        # and by keyword; we only ever construct the fake by keyword in the
        # driver, but accept the positional form too for robustness.
        self._target = target
        # ``args`` is the conventional Thread keyword name for the target's
        # positional tuple; the keyword-only ``args_kw`` above is defensive
        # against the (unlikely) case of ``threading.Thread(args=...)``
        # being called positionally with the same name as the
        # ``*args`` capture above.
        self._args: Tuple[Any, ...] = tuple(args_kw) if args_kw else ()
        self._kwargs = dict(kwargs) if kwargs else {}

    def start(self) -> None:
        if self._target is not None:
            self._target(*self._args, **self._kwargs)

    def is_alive(self) -> bool:
        return False

    def join(self, timeout: Any = None) -> None:  # pragma: no cover - defensive
        return None


def _make_thread_factory():
    """
    Return a callable usable as a ``threading.Thread`` replacement.

    ``threading.Thread`` is most often constructed by keyword
    (``Thread(target=..., args=..., daemon=True, name=...)``). The driver
    code uses exactly that shape. We forward the conventional ``args``
    keyword into ``_SyncFakeThread`` under the alias ``args_kw`` to avoid
    colliding with the ``*args`` capture in :class:`_SyncFakeThread`'s
    constructor (the alias lets us keep the parameter name unambiguous
    while still accepting the standard Thread call-shape from outside).
    """

    def _factory(*args: Any, **kwargs: Any) -> _SyncFakeThread:
        target = kwargs.pop("target", None)
        thread_args = kwargs.pop("args", ())
        thread_kwargs = kwargs.pop("kwargs", None)
        # Discard ``name`` / ``daemon`` / any other Thread-only kwargs.
        kwargs.pop("name", None)
        kwargs.pop("daemon", None)
        return _SyncFakeThread(
            target=target,
            args_kw=thread_args,
            kwargs=thread_kwargs,
        )

    return _factory


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------

# Move components in [-100, 100] per the task plan: well inside the
# Req 1.4 valid-input window so every move passes the no-op gate and
# actually reaches ``_dispatch_call``. (The Req 1.4 invalid-input branch
# is covered by Property 3 in ``test_kmbox_invalid_move.py``.)
_MOVE_FLOATS = st.floats(
    min_value=-100.0,
    max_value=100.0,
    allow_nan=False,
    allow_infinity=False,
)


def _method_call(
    name: str,
    args_strategy: st.SearchStrategy[Tuple[Any, ...]],
) -> st.SearchStrategy[Tuple[str, Tuple[Any, ...], bool]]:
    """Build a tagged-tuple strategy ``(name, args, should_raise)``.

    The ``should_raise`` boolean is consulted by the test body to flip
    the shared exception-injection latch around the driver method
    invocation, exercising Req 4.6 ("drop only that command, do not fall
    back").
    """
    return st.tuples(st.just(name), args_strategy, st.booleans())


# Each method-call shape is generated as a tagged tuple so the test body
# can ``match`` on the first element. Argument tuples are wrapped with
# ``st.tuples`` so the args entry is always a tuple (uniform shape across
# methods).
_METHOD_CALL_STRATEGY = st.one_of(
    # ``move(x, y)`` — Req 1.3 valid-input branch, exercises the
    # ``"move"`` key in both dispatch tables.
    _method_call("move", st.tuples(_MOVE_FLOATS, _MOVE_FLOATS)),
    # ``click()`` — exercises the ``send_click`` path which issues
    # ``_dispatch_call("left", 1)`` then ``_dispatch_call("left", 0)``.
    # Per the task plan: "Don't include rate-limit-affected click()
    # repetition issues" — we drive it through the same tables but the
    # driver's ``target_cps`` rate limiter may legitimately drop calls
    # within the window. Either outcome is fine for the property: a
    # dropped click contributes nothing to either side of the count
    # comparison.
    _method_call("click", st.just(())),
    # ``click_button(button)`` — full identifier set covers both
    # ``press_release`` (string) and edge (integer) branches of
    # ``_BUTTON_EDGE``.
    _method_call(
        "click_button", st.tuples(st.sampled_from(_CLICK_BUTTON_IDS))
    ),
    # ``mouse_down(button)`` / ``mouse_up(button)`` — full identifier
    # set per Req 4.3a.
    _method_call(
        "mouse_down", st.tuples(st.sampled_from(_HOLD_BUTTON_IDS))
    ),
    _method_call(
        "mouse_up", st.tuples(st.sampled_from(_HOLD_BUTTON_IDS))
    ),
    # ``key_press(vk_code, hold_ms)`` — VK 0x41 (A) is in the
    # ``_vk_to_hid`` table; hold_ms=0 keeps the deterministic Req 4.8
    # hold collapsed to ``time.sleep(0)``.
    _method_call("key_press", st.tuples(st.just(0x41), st.just(0))),
    # ``scroll(amount)`` — small integer wheel deltas.
    _method_call("scroll", st.tuples(st.integers(min_value=-10, max_value=10))),
)

_METHOD_CALL_LIST_STRATEGY = st.lists(
    _METHOD_CALL_STRATEGY, min_size=0, max_size=30
)


# ``max_examples=100`` matches the task plan's ``@settings(max_examples=100)``
# directive. ``deadline=None`` disables the per-example time budget — the
# property body invokes up to 30 driver methods against mocks, which is
# fast in absolute terms but Windows scheduler jitter can flag spurious
# deadline failures on CI.
_PROPERTY_SETTINGS = settings(
    max_examples=100,
    deadline=None,
    suppress_health_check=[
        HealthCheck.too_slow,
        # The kmNet mock and module-level patches are reinstalled per
        # Hypothesis example inside the test body, not via a
        # function-scoped fixture, so this health check is irrelevant to
        # this property — but the suppression is kept to match the rest
        # of the kmbox property-test suite.
        HealthCheck.function_scoped_fixture,
    ],
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _install_dispatch_side_effect(
    mock: MagicMock, raise_latch: List[bool]
) -> None:
    """
    Wire every relevant ``kmNet.*`` attribute on ``mock`` to consult a
    shared raise-latch.

    The latch (``raise_latch[0]``) is mutated by the test body around
    each driver method invocation: ``True`` while a method whose
    ``should_raise`` flag is set is in flight, ``False`` otherwise. Every
    ``kmNet.*`` mock attribute's ``side_effect`` is set to a closure that
    raises ``RuntimeError`` when the latch is True and returns ``0``
    (mirroring the vendor's success code) otherwise.

    Using a single shared latch — rather than per-attribute side effects
    — means the test does not need to predict which attribute a given
    driver method will reach. That keeps the exception-injection logic
    aligned with the property's intent (which is *what gets called*, not
    *which call raised*).
    """

    def _side_effect(*args: Any, **kwargs: Any) -> int:
        if raise_latch[0]:
            raise RuntimeError("injected_mock_failure")
        # Vendor functions return 0 on success; mirroring keeps the
        # mock's behaviour aligned with the real ``kmNet.*`` contract.
        return 0

    for attr_name in _ALL_DISPATCH_ATTRS:
        getattr(mock, attr_name).side_effect = _side_effect


def _reset_dispatch_call_history(mock: MagicMock) -> None:
    """
    Clear ``call_count`` / ``call_args_list`` on every dispatch attribute
    while preserving the ``side_effect`` configured by
    :func:`_install_dispatch_side_effect`.

    ``mock.reset_mock()`` (without ``side_effect=True``) preserves the
    side_effect by design, which is exactly what we need: the
    exception-injection wiring must survive the reset that clears any
    incidental ``kmNet.*`` calls made during driver construction.
    """
    for attr_name in _ALL_DISPATCH_ATTRS:
        getattr(mock, attr_name).reset_mock()


def _sum_call_counts(mock: MagicMock, attrs: Iterable[str]) -> int:
    """Total invocation count across the given ``mock.*`` attributes."""
    return sum(getattr(mock, a).call_count for a in attrs)


def _invoke_driver_method(
    driver: KmBoxNetDriver,
    method_name: str,
    args: Tuple[Any, ...],
) -> None:
    """
    Dispatch a single tagged method call against the driver.

    ``send_move`` re-raises UDP transmission failures per Req 1.8, so a
    raising mock attribute will propagate out of :meth:`move` /
    :meth:`move_relative`. Every other method (``click``,
    ``click_button``, ``mouse_down``, ``mouse_up``, ``key_press``,
    ``scroll``) catches and logs the exception internally per the
    existing public-API contract. We absorb the propagated ``move``
    exception here so the property loop continues; the property's
    correctness is independent of whether any individual call raised.
    """
    try:
        if method_name == "move":
            driver.move(*args)
        elif method_name == "click":
            driver.click(*args)
        elif method_name == "click_button":
            driver.click_button(*args)
        elif method_name == "mouse_down":
            driver.mouse_down(*args)
        elif method_name == "mouse_up":
            driver.mouse_up(*args)
        elif method_name == "key_press":
            driver.key_press(*args)
        elif method_name == "scroll":
            driver.scroll(*args)
        else:  # pragma: no cover - guarded by the strategy enumeration
            raise AssertionError(f"unknown method: {method_name!r}")
    except RuntimeError as e:
        # Req 1.8 — ``send_move`` re-raises UDP transmission failures.
        # The ``injected_mock_failure`` we surface inside the
        # ``raise_latch`` is the test-side analogue, so we tolerate it
        # here. Anything else is a real bug and should propagate.
        if str(e) != "injected_mock_failure":
            raise


# ---------------------------------------------------------------------------
# Property test
# ---------------------------------------------------------------------------


@pytest.mark.unit
@_PROPERTY_SETTINGS
@given(
    use_encryption=st.booleans(),
    method_calls=_METHOD_CALL_LIST_STRATEGY,
)
def test_encryption_flag_governs_send_site_routing(
    use_encryption: bool,
    method_calls: List[Tuple[str, Tuple[Any, ...], bool]],
) -> None:
    """
    Validates Req 4.1 / 4.2 / 4.4 / 4.5 / 4.6.

    For any sequence of public driver-method invocations — including
    individual invocations whose underlying ``kmNet.*`` call raises an
    exception — the encryption flag dictates which attribute table is
    consulted at every send-site:

    * ``use_encryption=True``  ⇒  zero invocations of any plaintext
      ``kmNet.{move, left, right, middle, wheel, keydown, keyup}``.
    * ``use_encryption=False`` ⇒  zero invocations of any encrypted
      ``kmNet.enc_{move, left, right, middle, wheel, keydown, keyup}``.

    Per-call exceptions are injected via a shared raise-latch toggled
    around each method invocation; the driver's internal exception
    handling — log-and-swallow for the public-API methods, re-raise from
    ``send_move`` per Req 1.8 — is exercised in both branches and MUST
    NOT cause a fall-back to the opposite table (Req 4.6).
    """
    # ----- Install kmNet mock so ``_connect()`` lands in CONNECTED ---------
    # The driver is constructed inside the patched ``threading.Thread``
    # context below so the connect worker runs synchronously; with the
    # mock returning ``0`` immediately the bounded ``queue.get(timeout=5.0)``
    # in ``_connect()`` resolves on the first poll and the driver
    # transitions to CONNECTED.
    original_kmnet = kmbox_net_driver.kmNet
    mock_kmnet = MagicMock(name="kmNet")
    mock_kmnet.init.return_value = 0

    # The shared raise-latch consulted by every dispatch-attribute
    # ``side_effect``. Single-element list so the closure can mutate it
    # without ``nonlocal``.
    raise_latch: List[bool] = [False]
    _install_dispatch_side_effect(mock_kmnet, raise_latch)

    kmbox_net_driver.kmNet = mock_kmnet
    try:
        # Patch ``threading.Thread`` and ``time.sleep`` for the entire
        # test (construction + method loop). The thread substitution is
        # safe during construction because ``kmNet.init`` returns ``0``
        # via the mock, so the synchronous fake worker completes inline.
        # The ``time.sleep`` substitution suppresses the click hold and
        # keyboard hold; the rate-limit logic in ``click`` reads
        # ``time.monotonic`` (left untouched) and may legitimately drop
        # clicks within the ``1.0 / target_cps`` window — that is fine
        # for this property because a dropped click contributes nothing
        # to either side of the count comparison.
        with patch(
            "input.kmbox_net_driver.threading.Thread",
            new=_make_thread_factory(),
        ), patch(
            "input.kmbox_net_driver.time.sleep",
            new=lambda *_a, **_kw: None,
        ):
            driver = KmBoxNetDriver(
                ip=_TEST_IP,
                port=_TEST_PORT,
                uuid=_TEST_UUID,
                use_encryption=use_encryption,
                # ``target_cps=1000`` keeps the click rate-limit window
                # at 1 ms. Most clicks within a short Hypothesis-driven
                # sequence will still drop, but that is irrelevant to
                # the property — see commentary above.
                target_cps=1000.0,
            )

            # Precondition: with the mocked ``kmNet.init`` returning 0
            # the driver MUST land in CONNECTED, otherwise
            # ``_dispatch_call`` short-circuits and every subsequent
            # call is silently dropped (which would make the property
            # vacuously true and hide a routing regression).
            assert driver.connection_status is ConnectionStatus.CONNECTED, (
                "fixture precondition failed: driver did not reach "
                "CONNECTED state with mocked kmNet.init returning 0"
            )

            # Discard any incidental ``kmNet.*`` calls made during
            # construction (none expected today, but the reset is cheap
            # insurance against future ``__init__`` evolution). The
            # ``side_effect`` wiring is preserved.
            _reset_dispatch_call_history(mock_kmnet)

            # ----- Drive the method-call sequence ----------------------
            for method_name, args, should_raise in method_calls:
                # Req 4.6 — toggle the latch only around this single
                # invocation so an injected failure cannot bleed across
                # method boundaries.
                raise_latch[0] = should_raise
                try:
                    _invoke_driver_method(driver, method_name, args)
                finally:
                    raise_latch[0] = False

        # ----- Property assertion ----------------------------------------
        plaintext_calls = _sum_call_counts(mock_kmnet, _PLAINTEXT_ATTRS)
        encrypted_calls = _sum_call_counts(mock_kmnet, _ENCRYPTED_ATTRS)

        if use_encryption:
            # Req 4.1 / 4.2 / 4.4 / 4.5 — encrypted mode emits ZERO
            # plaintext calls; Req 4.6 — a raised exception inside an
            # encrypted call MUST NOT cause the driver to fall back to
            # the plaintext table on subsequent invocations.
            assert plaintext_calls == 0, (
                "Property 1 violated: use_encryption=True emitted "
                f"{plaintext_calls} plaintext kmNet call(s) across "
                f"{len(method_calls)} method invocation(s); "
                f"per-attribute counts: "
                + ", ".join(
                    f"{a}={getattr(mock_kmnet, a).call_count}"
                    for a in _PLAINTEXT_ATTRS
                )
                + f"; method_calls={method_calls!r}"
            )
        else:
            # Symmetric assertion: plaintext mode emits ZERO encrypted
            # calls.
            assert encrypted_calls == 0, (
                "Property 1 violated: use_encryption=False emitted "
                f"{encrypted_calls} encrypted kmNet call(s) across "
                f"{len(method_calls)} method invocation(s); "
                f"per-attribute counts: "
                + ", ".join(
                    f"{a}={getattr(mock_kmnet, a).call_count}"
                    for a in _ENCRYPTED_ATTRS
                )
                + f"; method_calls={method_calls!r}"
            )
    finally:
        # Restore the module-level ``kmNet`` binding regardless of test
        # outcome so subsequent tests in the same session are not
        # contaminated by this test's mock.
        kmbox_net_driver.kmNet = original_kmnet
