"""
Real-NPU smoke test for ``engines.qnn_provider.QNNProvider``.

Feature: npu-qnn-provider, Smoke: real-NPU inference latency.

This module exercises the actual Qualcomm Hexagon NPU path end-to-end. It is
gated two ways so it stays runnable on x86_64 CI/dev hosts:

    1. ``pytest.importorskip("onnxruntime")`` at module scope — skips the entire
       module when ``onnxruntime`` is not importable (Req 9.5, Req 7.5).
    2. ``pytestmark = pytest.mark.skipif(not has_qnn(), ...)`` — skips every test
       when ``QNNExecutionProvider`` is absent from
       ``onnxruntime.get_available_providers()`` (Req 9.5).

The single test inside is a *soft* latency anchor: a ``< 50 ms`` ceiling that
documents the latency budget without being a CI gate. Steady-state NPU inference
on Snapdragon X is expected to land near 5 ms; a failure here flags an
investigation, not a regression block.

Validates: Requirements 9.5
"""

from __future__ import annotations

import numpy as np
import pytest

# Module-scope import gate — Req 9.5 / Req 7.5.
pytest.importorskip("onnxruntime")

from engines.qnn_provider import QNNProvider, has_qnn  # noqa: E402

# Module-scope skip gate — Req 9.5. Evaluated at collection time so the entire
# module is reported as SKIPPED on hosts where the QNN execution provider is not
# registered with ONNX Runtime (i.e. every x86_64 dev host).
pytestmark = pytest.mark.skipif(
    not has_qnn(),
    reason="QNNExecutionProvider not available",
)


def test_qnn_smoke_real_npu_single_inference() -> None:
    """
    Feature: npu-qnn-provider, Smoke: real-NPU inference latency.

    Construct a real ``QNNProvider`` against the production ONNX artifact, run a
    single inference on a randomized 1080p BGR frame, and soft-assert the latency
    against the documented < 50 ms ceiling. Failure is informational — it
    points at an investigation (thermal throttling, HTP performance mode drift,
    cold-cache miss, or a model regression) rather than a hard CI gate.

    Validates: Requirements 9.5
    """
    # Use the FP32 baseline for the smoke. The FP16 variant generated by
    # tools/convert_model_fp16.py was empirically slower on QNN HTP because
    # post-conversion Cast nodes around blocked Resize ops increase DMA
    # bandwidth. A real FP16 win would require a native PyTorch export.
    model_path = "./models/v11n-416-2.onnx"
    provider = QNNProvider(model_path, imgsz=416, conf=0.55)
    assert provider.load() is True

    try:
        # Capture-frame-shaped random BGR input. ``randint`` over ``[0, 256)``
        # exercises the full uint8 range so the FP16 normalize-and-cast path in
        # ``preprocess`` is hit with realistic values.
        frame = np.random.randint(
            0, 256, size=(1080, 1920, 3), dtype=np.uint8
        )

        dets, ms = provider.infer(frame)

        # Soft latency anchor — documents the budget. The 5 ms steady-state
        # target lives in the message so a failure surfaces both the actual
        # measurement and the expected order of magnitude.
        assert ms < 50.0, (
            f"NPU inference took {ms:.2f} ms (target < 5 ms steady-state)"
        )

        # Sanity on the contract — the module-scope smoke is primarily about
        # latency, but a malformed return tuple would mask a real bug.
        assert isinstance(dets, list)
        assert isinstance(ms, float)
    finally:
        # Idempotent teardown — must not raise even if ``infer`` blew up above.
        provider.release()
