"""Integration tests for the Audit_Document invariants.

Task 1.3 of the ``single-config-streamlining`` spec verifies that
``.kiro/specs/single-config-streamlining/audit.md`` satisfies the three
invariants required by Requirements 1.1, 1.2, 1.3, 1.4 and 1.10:

* **Coverage invariant** — every ``.py`` file in the workspace (excluding
  ``.archive/``, ``htmlcov/``, ``.pytest_cache/``, ``__pycache__/`` and
  ``.kiro/``) appears exactly once in the summary table under the
  ``## Tabella riepilogativa`` section of ``audit.md``.
* **Partition invariant** — every row in the summary table is classified
  as either ``KEEP`` or ``REMOVE``; no ``EVALUATE`` residual remains
  (Req 1.7).
* **Consistency invariant** — no file classified ``KEEP`` imports a file
  classified ``REMOVE``. This is a *post-refactoring* invariant: the
  Audit_Document explicitly acknowledges (under the "Invariante di
  coerenza (post-refactoring)" section) that a small set of files
  currently import REMOVE modules and will be cleaned up by later tasks
  (2.2, 3.2, 4.2, 5.2, 12.1, 13.1, 14.1). The test therefore asserts
  that the current set of KEEP→REMOVE violations is a *subset* of the
  acknowledged set, so the invariant strengthens monotonically as
  cleanup tasks run.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple

import pytest


# --- Workspace layout -----------------------------------------------------

_WORKSPACE = Path(__file__).resolve().parents[2]
_AUDIT_PATH = (
    _WORKSPACE
    / ".kiro"
    / "specs"
    / "single-config-streamlining"
    / "audit.md"
)

# Folders whose ``.py`` files must not be considered part of the
# Target_Configuration surface (matches the exclusions used to produce
# the Audit_Document plus ``.kiro/`` which hosts spec-side scripts).
_EXCLUDED_DIRS: Tuple[str, ...] = (
    ".archive",
    "htmlcov",
    ".pytest_cache",
    "__pycache__",
    ".kiro",
)

# Files introduced by later tasks of this same spec. They legitimately
# exist in the workspace but were not present when the Audit_Document
# was generated by task 1.1/1.2, so they must be excluded from the
# coverage check (they are implicitly KEEP as new artifacts of the
# streamlining effort).
_SPEC_ARTIFACT_FILES: Set[str] = {
    "tests/integration/test_audit_document.py",  # this file (task 1.3)
    "tools/yaml_helper.py",                      # task 11.1
    "tools/verify_refactoring.py",               # task 17.1
}

# KEEP files that are permitted to import REMOVE modules *before* the
# fases 2-3 cleanup tasks run. Each entry is a workspace-relative POSIX
# path. The authoritative list lives in ``audit.md`` under the
# "Invariante di coerenza (post-refactoring)" section.
_ACKNOWLEDGED_PRE_REFACTOR_VIOLATORS: Set[str] = {
    "capture/__init__.py",       # cleaned by task 2.2
    "engines/__init__.py",       # cleaned by task 4.2
    "input/__init__.py",         # cleaned by task 3.2
    "utils/__init__.py",         # cleaned by task 5.2
    "main.py",                   # cleaned by task 12.1
    "engines/coordinator.py",    # cleaned by task 13.1
    # gui/*.py — cleaned by task 14.1 (added dynamically below)
}


# --- Audit parsing --------------------------------------------------------

_TABLE_HEADER_RE = re.compile(r"^\s*## Tabella riepilogativa\s*$", re.MULTILINE)
# Matches a row like: | `path/to/file.py` | `KEEP` | reason text |
_TABLE_ROW_RE = re.compile(
    r"^\|\s*`(?P<file>[^`]+)`\s*\|\s*`(?P<cls>[^`]+)`\s*\|\s*(?P<reason>.*?)\s*\|\s*$"
)


def _parse_summary_table(audit_text: str) -> Dict[str, str]:
    """Return a mapping ``file -> classification`` from the summary table.

    The summary table lives under the ``## Tabella riepilogativa``
    heading and ends at the next ``##`` heading. Only rows whose first
    cell is a backticked path and second cell is a backticked
    classification are considered (header and separator rows are
    skipped automatically).
    """
    header_match = _TABLE_HEADER_RE.search(audit_text)
    assert header_match is not None, (
        "audit.md is missing the '## Tabella riepilogativa' section; "
        "task 1.1 must produce it and task 1.2 must keep it."
    )
    start = header_match.end()
    # Stop at the next '## ' heading (not deeper levels).
    next_heading = re.search(r"^\s*##\s", audit_text[start:], re.MULTILINE)
    end = start + next_heading.start() if next_heading else len(audit_text)
    section = audit_text[start:end]

    rows: Dict[str, str] = {}
    for line in section.splitlines():
        m = _TABLE_ROW_RE.match(line)
        if not m:
            continue
        file_path = m.group("file").strip()
        classification = m.group("cls").strip()
        # Skip a stray header row if someone wrapped headers in backticks.
        if classification.lower() == "classification":
            continue
        rows[file_path] = classification
    assert rows, (
        "The summary table under '## Tabella riepilogativa' is empty; "
        "task 1.1 must populate it with one row per workspace .py file."
    )
    return rows


# --- Workspace scan -------------------------------------------------------

def _iter_workspace_python_files() -> Iterable[Path]:
    """Yield every ``.py`` file in the workspace, skipping excluded dirs."""
    for path in _WORKSPACE.rglob("*.py"):
        rel_parts = path.relative_to(_WORKSPACE).parts
        if any(part in _EXCLUDED_DIRS for part in rel_parts):
            continue
        yield path


def _workspace_rel(path: Path) -> str:
    """Return a POSIX workspace-relative path (matches audit.md format)."""
    return path.relative_to(_WORKSPACE).as_posix()


# --- Import resolution ----------------------------------------------------

def _build_module_to_file_map(
    py_files: Iterable[Path],
) -> Dict[str, str]:
    """Map ``a.b.c`` dotted module names to workspace-relative file paths.

    ``pkg/__init__.py`` maps to ``pkg``; ``pkg/mod.py`` maps to
    ``pkg.mod``. This mirrors Python's import semantics for top-level
    packages rooted at the workspace root.
    """
    module_map: Dict[str, str] = {}
    for path in py_files:
        rel = _workspace_rel(path)
        parts = rel.split("/")
        if parts[-1] == "__init__.py":
            mod = ".".join(parts[:-1])
        else:
            mod = ".".join(parts[:-1] + [parts[-1][:-3]])
        if mod:
            module_map[mod] = rel
    return module_map


def _package_of(rel_path: str) -> str:
    """Return the dotted package name that hosts ``rel_path``.

    For ``pkg/mod.py`` returns ``pkg``; for ``pkg/sub/__init__.py``
    returns ``pkg.sub``; for top-level ``mod.py`` returns ``""``.
    """
    parts = rel_path.split("/")
    if parts[-1] == "__init__.py":
        return ".".join(parts[:-1])
    return ".".join(parts[:-1]) if len(parts) > 1 else ""


def _resolve_relative(
    package: str, module: str | None, level: int
) -> str | None:
    """Resolve a relative ``from`` import to an absolute dotted module."""
    if level <= 0:
        return module or None
    pkg_parts = package.split(".") if package else []
    # level=1 means "current package"; level=2 means "parent", etc.
    if level > len(pkg_parts) + 1:
        return None
    base = pkg_parts[: len(pkg_parts) - (level - 1)] if level > 1 else pkg_parts
    if module:
        return ".".join([*base, module]) if base else module
    return ".".join(base) if base else None


def _imports_in_file(path: Path) -> List[Tuple[str, str | None, int]]:
    """Return a list of ``(module_or_None, name_or_None, level)`` tuples.

    * ``import a.b`` → ``("a.b", None, 0)``
    * ``from a.b import c`` → ``("a.b", "c", 0)``
    * ``from . import x`` inside package ``pkg`` → ``(None, "x", 1)``
    * ``from .mod import x`` inside ``pkg`` → ``("mod", "x", 1)``
    """
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return []

    results: List[Tuple[str, str | None, int]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                results.append((alias.name, None, 0))
        elif isinstance(node, ast.ImportFrom):
            module = node.module  # may be None for "from . import x"
            level = node.level or 0
            for alias in node.names:
                results.append((module, alias.name, level))
    return results


def _resolve_to_workspace_file(
    module: str | None,
    name: str | None,
    level: int,
    package: str,
    module_map: Dict[str, str],
) -> str | None:
    """Resolve one AST import record to a workspace-relative file path.

    Returns ``None`` for third-party imports or unresolved relatives.
    If both ``module`` and ``module.name`` resolve, ``module.name`` is
    preferred because ``from pkg import submod`` imports the submodule.
    """
    abs_module = _resolve_relative(package, module, level)

    candidates: List[str] = []
    if abs_module and name:
        candidates.append(f"{abs_module}.{name}")
    if abs_module:
        candidates.append(abs_module)
    if name and not abs_module and level == 0:
        # Plain ``import name`` (AST: Import, level is always 0)
        candidates.append(name)

    for cand in candidates:
        if cand in module_map:
            return module_map[cand]
    return None


# --- Fixtures -------------------------------------------------------------

@pytest.fixture(scope="module")
def audit_text() -> str:
    assert _AUDIT_PATH.exists(), (
        f"audit.md not found at {_AUDIT_PATH}; task 1.1 must produce it "
        "before task 1.3 can run."
    )
    return _AUDIT_PATH.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def summary_table(audit_text: str) -> Dict[str, str]:
    return _parse_summary_table(audit_text)


@pytest.fixture(scope="module")
def workspace_py_files() -> List[Path]:
    return sorted(_iter_workspace_python_files())


# --- Tests ----------------------------------------------------------------

@pytest.mark.integration
def test_coverage_invariant(
    summary_table: Dict[str, str], workspace_py_files: List[Path]
) -> None:
    """Every workspace ``.py`` file appears exactly once in the table.

    The test tolerates two benign asymmetries:

    * ``.py`` files introduced by later tasks of this same spec
      (see ``_SPEC_ARTIFACT_FILES``) legitimately exist on disk without
      appearing in the audit; they are excluded from the check.
    * After fases 2-3 run, REMOVE files will be physically deleted; the
      audit still lists them (that is exactly what ``audit.md`` is for).
      So extra rows whose classification is REMOVE are tolerated.
    """
    workspace_rel = {
        _workspace_rel(p)
        for p in workspace_py_files
        if _workspace_rel(p) not in _SPEC_ARTIFACT_FILES
    }
    table_rel = set(summary_table.keys())

    missing = sorted(workspace_rel - table_rel)
    extra = sorted(
        rel
        for rel in (table_rel - workspace_rel)
        if summary_table[rel] != "REMOVE"
    )

    assert not missing, (
        "Coverage invariant violated: the following workspace .py files "
        "are not classified in audit.md#Tabella riepilogativa:\n  - "
        + "\n  - ".join(missing)
    )
    assert not extra, (
        "Coverage invariant violated: audit.md classifies KEEP files "
        "that do not exist in the workspace (or live under an excluded "
        "folder):\n  - " + "\n  - ".join(extra)
    )

    # Exactly once: the parser already dedups by key, so reparse the raw
    # table lines to catch accidental duplicates that would collide.
    raw = _AUDIT_PATH.read_text(encoding="utf-8")
    header_match = _TABLE_HEADER_RE.search(raw)
    start = header_match.end()
    next_heading = re.search(r"^\s*##\s", raw[start:], re.MULTILINE)
    end = start + next_heading.start() if next_heading else len(raw)
    files_in_order = [
        m.group("file").strip()
        for line in raw[start:end].splitlines()
        for m in [_TABLE_ROW_RE.match(line)]
        if m and m.group("cls").strip().lower() != "classification"
    ]
    duplicates = sorted({f for f in files_in_order if files_in_order.count(f) > 1})
    assert not duplicates, (
        "Coverage invariant violated: files listed more than once in the "
        "summary table:\n  - " + "\n  - ".join(duplicates)
    )


@pytest.mark.integration
def test_partition_invariant(summary_table: Dict[str, str]) -> None:
    """Only KEEP and REMOVE classifications; no EVALUATE residuals."""
    allowed = {"KEEP", "REMOVE"}
    bad = {
        path: cls
        for path, cls in summary_table.items()
        if cls not in allowed
    }
    assert not bad, (
        "Partition invariant violated: the summary table must classify "
        "every file as KEEP or REMOVE (task 1.2 resolves all EVALUATE). "
        "Non-conforming rows:\n  - "
        + "\n  - ".join(f"{k}: {v}" for k, v in sorted(bad.items()))
    )


@pytest.mark.integration
def test_consistency_invariant_keep_does_not_import_removed(
    summary_table: Dict[str, str], workspace_py_files: List[Path]
) -> None:
    """No KEEP file imports a REMOVE file (post-refactoring invariant).

    Until fases 2-3 run, a bounded, acknowledged set of KEEP files still
    imports REMOVE modules (see audit.md "Invariante di coerenza
    (post-refactoring)"). The test asserts that the *current* set of
    violating KEEP files is a subset of that acknowledged set, so the
    invariant strengthens monotonically as cleanup tasks 2.2, 3.2, 4.2,
    5.2, 12.1, 13.1 and 14.1 complete.
    """
    keep_files = {
        p for p, cls in summary_table.items() if cls == "KEEP"
    }
    remove_files = {
        p for p, cls in summary_table.items() if cls == "REMOVE"
    }
    workspace_py_rel = {_workspace_rel(p) for p in workspace_py_files}
    module_map = _build_module_to_file_map(workspace_py_files)

    # gui/*.py are permitted to still reference REMOVE modules pre-task 14.1.
    acknowledged = set(_ACKNOWLEDGED_PRE_REFACTOR_VIOLATORS)
    acknowledged |= {
        rel for rel in workspace_py_rel
        if rel.startswith("gui/") and rel in keep_files
    }

    violations: Dict[str, Set[str]] = {}
    for rel in sorted(keep_files):
        abs_path = _WORKSPACE / rel
        # File might be classified KEEP in the audit but missing from disk
        # (shouldn't happen after coverage test passes, but be defensive).
        if not abs_path.is_file():
            continue
        package = _package_of(rel)
        for module, name, level in _imports_in_file(abs_path):
            resolved = _resolve_to_workspace_file(
                module, name, level, package, module_map
            )
            if resolved is not None and resolved in remove_files:
                violations.setdefault(rel, set()).add(resolved)

    unexpected = {
        keep: targets
        for keep, targets in violations.items()
        if keep not in acknowledged
    }
    if unexpected:
        lines = [
            f"  - {keep} imports REMOVE: {sorted(targets)}"
            for keep, targets in sorted(unexpected.items())
        ]
        pytest.fail(
            "Consistency invariant violated: KEEP files importing REMOVE "
            "modules outside the acknowledged pre-refactoring set. Either "
            "clean the import or add the file to the audit.md "
            "'Invariante di coerenza (post-refactoring)' section.\n"
            + "\n".join(lines)
        )
